name: Build TiddlyWiki Add-on

'on':
  push:
    branches: [main]
    tags: ['v*']
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  build:
    name: Build TiddlyWiki add-on
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Compute image namespace
        id: vars
        run: |
          echo "namespace=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_OUTPUT"

      - name: Log in to the Container registry
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build TiddlyWiki add-on
        uses: home-assistant/builder@54867a1d0e8d244e6495d8920138ba14b33a4471
        with:
          args: |
            --target tiddlywiki \
            --amd64 --aarch64 --armhf --armv7 --i386 \
            --docker-hub ${{ env.REGISTRY }}/${{ steps.vars.outputs.namespace }}
