name: Build TiddlyWiki Add-on

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  build:
    name: Build TiddlyWiki add-on
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build TiddlyWiki add-on
        uses: home-assistant/builder@master
        with:
          args: |
            --target /data/tiddlywiki \
            --all \
            --docker-hub ${{ env.REGISTRY }}/bensweetervest
