name: Build and Push Add-ons

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  information:
    name: Gather add-on information
    runs-on: ubuntu-latest
    outputs:
      changed_addons: ${{ steps.changed_addons.outputs.addons }}
      changed: ${{ steps.changed_addons.outputs.changed }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed_files
        uses: jitterbit/get-changed-files@v1

      - name: Find add-on directories
        id: addons
        uses: home-assistant/actions/helpers/find-addons@master

      - name: Get changed add-ons
        id: changed_addons
        run: |
          declare -a changed_addons
          for addon in ${{ steps.addons.outputs.addons }}; do
            if [[ "${{ steps.changed_files.outputs.all }}" =~ $addon ]]; then
              changed_addons+=("\"${addon}\",");
            fi
          done
          changed=$(echo ${changed_addons[@]} | rev | cut -c 2- | rev)
          if [[ ${#changed_addons[@]} -gt 0 ]]; then
            echo "Changed add-ons: $changed";
            echo "changed=true" >> $GITHUB_OUTPUT;
            echo "addons=[$changed]" >> $GITHUB_OUTPUT;
          else
            echo "No add-on had any changes"
            echo "changed=false" >> $GITHUB_OUTPUT;
          fi

  build:
    name: Build ${{ matrix.addon }} add-on
    if: needs.information.outputs.changed == 'true'
    needs: information
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        addon: ${{ fromJson(needs.information.outputs.changed_addons) }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build ${{ matrix.addon }} add-on
        uses: home-assistant/builder@master
        with:
          args: |
            --target /data/${{ matrix.addon }} \
            --all \
            --with-codenotary \
            --docker-hub ${{ env.REGISTRY }}/bensweetervest

  # Also build on workflow_dispatch or when no files changed (for manual builds)
  build-all:
    name: Build all add-ons (manual/forced)
    if: github.event_name == 'workflow_dispatch' || (needs.information.outputs.changed == 'false' && github.event_name == 'push')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Find add-on directories
        id: addons
        uses: home-assistant/actions/helpers/find-addons@master

      - name: Build all add-ons
        uses: home-assistant/builder@master
        with:
          args: |
            --target /data/tiddlywiki \
            --all \
            --with-codenotary \
            --docker-hub ${{ env.REGISTRY }}/bensweetervest
