yamlname: Build Add-ons

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  information:
    name: Gather add-on information
    runs-on: ubuntu-latest
    outputs:
      changed_addons: ${{ steps.changed_addons.outputs.addons }}
      changed: ${{ steps.changed_addons.outputs.changed }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed_files
        uses: jitterbit/get-changed-files@v1

      - name: Find add-on directories
        id: addons
        uses: home-assistant/actions/helpers/find-addons@master

      - name: Get changed add-ons
        id: changed_addons
        run: |
          declare -a changed_addons
          for addon in ${{ steps.addons.outputs.addons }}; do
            if [[ "${{ steps.changed_files.outputs.all }}" =~ $addon ]]; then
              changed_addons+=("\"${addon}\",");
            fi
          done
          changed=$(echo ${changed_addons[@]} | rev | cut -c 2- | rev)
          if [[ ${#changed_addons[@]} -gt 0 ]]; then
            echo "Changed add-ons: $changed";
            echo "changed=true" >> $GITHUB_OUTPUT;
            echo "addons=[$changed]" >> $GITHUB_OUTPUT;
          else
            echo "No add-on had any changes"
            echo "changed=false" >> $GITHUB_OUTPUT;
          fi

  build:
    name: Build ${{ matrix.addon }} add-on
    if: needs.information.outputs.changed == 'true'
    needs: information
    runs-on: ubuntu-latest
    strategy:
      matrix:
        addon: ${{ fromJson(needs.information.outputs.changed_addons) }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Build ${{ matrix.addon }} add-on
        uses: home-assistant/builder@master
        with:
          args: |
            --target /data/${{ matrix.addon }} \
            --generic latest
            
